### ISSUE TITLE
CSVに記録するマップ名を内部名称ではなく日本語名に

### ISSUE THREAD

**Issue by levelnineteen** [levelnineteen/tos_speedrun#6]
したいんだけど、取得の仕方がわかりません。

**Comment by torahamu** [comment]
ちょっと試してみました。

こっちはtosクライアントだけの表示なら大丈夫ですが、実際には内部IDなので外に書き出すとなるとダメだと思います。
local mapClassName = session.GetMapName();
local mapprop = geMapTable.GetMapProp(mapClassName);
print(mapprop:GetName())

多分この書き方みたいに、dictionary.ReplaceDicIDInCompStr使えばいけます

local mapClassName = session.GetMapName();
local mapprop = geMapTable.GetMapProp(mapClassName);
local mapName = dictionary.ReplaceDicIDInCompStr(mapprop:GetName());
print(mapName)

![default](https://cloud.githubusercontent.com/assets/23138318/20644959/d29bdc44-b48d-11e6-9576-e1f44cddbfcb.png)

**Comment by levelnineteen** [comment]
ありがとうございます！　ものすごく分かりやすかったです。　反映させていただきました！
